# Generated by Django 5.2.7 on 2025-11-23 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('type', models.CharField(choices=[('logistics', 'Логистика'), ('manufacturer', 'Производитель'), ('retail', 'Розница'), ('government', 'Государственный')], max_length=20, verbose_name='Отраслевая принадлежность')),
                ('address', models.JSONField(blank=True, help_text='Структурированный адрес: {region, city, street, building, postcode}', null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название заказчика')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='logistics.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('assigned', 'Назначен'), ('loading', 'Погрузка'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('delayed', 'Задержан')], default='created', max_length=20, verbose_name='Статус')),
                ('cargo_type', models.CharField(max_length=100, verbose_name='Тип груза')),
                ('cargo_mass_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Масса груза (кг)')),
                ('cargo_volume_m3', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Объём груза (м³)')),
                ('payment_terms', models.CharField(blank=True, help_text='Например: "100% предоплата", "наличные при получении"', max_length=100, null=True, verbose_name='Условия оплаты')),
                ('pickup_datetime', models.DateTimeField(verbose_name='Плановое время забора')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Плановое время доставки')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расстояние (км)')),
                ('planned_route', models.TextField(blank=True, help_text='Координаты маршрута (GEOGRAPHY LINESTRING в PostGIS, здесь TextField)', null=True, verbose_name='Маршрут')),
                ('delay_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина задержки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='logistics.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал (диспетчер)')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма заказчику')),
                ('driver_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Выплата водителю')),
                ('third_party_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Погрузка, парковка, экспедитор', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сторонние расходы')),
                ('profit', models.DecimalField(decimal_places=2, editable=False, help_text='Вычисляется как client_cost - driver_cost - third_party_cost', max_digits=12, verbose_name='Прибыль')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('payment_plan', models.JSONField(blank=True, help_text='Массив объектов с датой, суммой и статусом оплаты', null=True, verbose_name='График оплат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='logistics.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Финансовые данные',
                'verbose_name_plural': 'Финансовые данные',
                'db_table': 'financials',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('invoice', 'Счёт'), ('act', 'Акт'), ('upd', 'УПД'), ('ttn', 'ТТН'), ('custom', 'Прочий')], max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер документа')),
                ('issued_at', models.DateField(verbose_name='Дата выставления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('signed', 'Подписан'), ('paid', 'Оплачен')], default='draft', max_length=20, verbose_name='Статус')),
                ('file_url', models.URLField(blank=True, help_text='Ссылка на PDF-файл во внешнем хранилище', max_length=500, null=True, verbose_name='Ссылка на файл')),
                ('data', models.JSONField(help_text='Структурированные реквизиты, суммы, подписи', verbose_name='Данные документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logistics.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('assigned', 'Назначен'), ('loaded', 'Загружен'), ('departed', 'Отправлен'), ('temperature_violation', 'Нарушение температурного режима'), ('delivered', 'Доставлен'), ('document_signed', 'Документ подписан'), ('status_changed', 'Изменение статуса'), ('location_update', 'Обновление местоположения')], max_length=50, verbose_name='Тип события')),
                ('event_data', models.JSONField(blank=True, help_text='Дополнительные данные: координаты, скорость, уровень батареи датчика и т.д.', null=True, verbose_name='Данные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие по заказу',
                'verbose_name_plural': 'События по заказам',
                'db_table': 'order_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_number', models.CharField(help_text='Уникальный в рамках компании', max_length=20, verbose_name='Гос. номер')),
                ('type', models.CharField(help_text='Например: "рефрижератор", "фура", "газель"', max_length=50, verbose_name='Тип ТС')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка и модель')),
                ('capacity_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грузоподъёмность (кг)')),
                ('capacity_m3', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Объём кузова (м³)')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('in_trip', 'В рейсе'), ('maintenance', 'На обслуживании'), ('blocked', 'Заблокирован')], default='available', max_length=20, verbose_name='Статус')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'db_table': 'vehicles',
                'unique_together': {('company', 'reg_number')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
