# Generated by Django 5.2.7 on 2025-11-13 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название груза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер лицензии')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Транспортное средство')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('busy', 'В рейсе')], default='available', max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('end_point', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_transit', 'В пути'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='created', max_length=20)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cargo')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
            ],
        ),
    ]
