# Generated by Django 5.2.7 on 2025-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, help_text='Адрес или название точки назначения', max_length=255, null=True, verbose_name='Пункт назначения'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(blank=True, help_text='Адрес или название точки отправления', max_length=255, null=True, verbose_name='Пункт отправления'),
        ),
    ]
