# Generated by Django 5.2.7 on 2025-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_order_destination_order_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed_by_driver',
            field=models.BooleanField(default=False, help_text='Отмечается True когда водитель открывает заказ', verbose_name='Просмотрен водителем'),
        ),
    ]
