# Generated by Django 5.2.7 on 2025-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_order_is_viewed_by_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cargo_volume_m3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_m3',
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость перевозки', max_digits=10, null=True, verbose_name='Договоренная стоимость'),
        ),
    ]
