# Generated by Django 5.2.7 on 2025-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_order_cargo_volume_m3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Назначен'), ('loaded', 'Загружен'), ('departed', 'Отправлен'), ('temperature_violation', 'Нарушение температурного режима'), ('delivered', 'Доставлен'), ('document_signed', 'Документ подписан'), ('status_changed', 'Изменение статуса'), ('payment_updated', 'Обновление оплаты'), ('location_update', 'Обновление местоположения')], max_length=50, verbose_name='Тип события'),
        ),
    ]
