# Generated by Django 5.2.7 on 2025-11-30 15:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='fuel_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Расходы на топливо'),
        ),
        migrations.AddField(
            model_name='financial',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Полученная сумма'),
        ),
    ]
