# Generated by Django 5.2.7 on 2025-12-01 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_financial_fuel_expenses_financial_received_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='received_amount',
        ),
        migrations.AlterField(
            model_name='financial',
            name='fuel_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Расходы на топливо'),
        ),
    ]
