# Generated by Django 5.2.7 on 2025-12-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_financial_received_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='payment_plan',
        ),
    ]
