# Generated by Django 5.2.7 on 2025-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dispatcher', 'Диспетчер'), ('driver', 'Водитель'), ('customer', 'Заказчик'), ('manager', 'Руководитель')], default='customer', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
